[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[packages]
networkx = "*"
numpy = "*"
pandas = "*"
scikit-learn = "*"
scipy = "*"
gensim = "*"
keras = "*"
tensorflow = "==2.4.2"

psycopg2-binary = "==2.8.6" # https://stackoverflow.com/questions/38807296/django-1-9-2-assertionerror-database-connection-isnt-set-to-utc
redis = "*"
celery = "*"
gunicorn = "*"
python-memcached = "*"

pymzml = "*"
ChemSpiPy = "*"
jsonpickle = "*"
tqdm = "*"
requests = "*"

django = "==3.0.6" # https://github.com/glasgowcompbio/ms2ldaviz/issues/169
django-extensions = "*"
django-grappelli = "*"
django-markdown2 = "*"
django-model-utils = "*"
django-ipware = "*"
django-debug-toolbar = "*"
django-debug-toolbar-force = "*"
django-countries = "*"

[dev-packages]

[requires]
python_version = "3.8"

[scripts]
runcelery = "/bin/bash -c 'cd ms2ldaviz && exec ./start_celery_prod.sh'"
